# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Coatjava-CI

on:
  pull_request:
  push:
    branches: [ development ]
    tags: [ '*' ]
  schedule:
    # NOTE: From what I read, the email notification for cron can only go
    #       to the last committer of this file!!!!!
    - cron: '0 22 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  java_version: 17
  java_distribution: zulu
  groovy_version: 4.x

jobs:

  # build
  #############################################################################

  build:
    strategy:
      fail-fast: true
      matrix:
        runner:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java_version }}
          distribution: ${{ env.java_distribution }}
      - name: javadoc version
        run: javadoc --version
